### ISSUE TITLE
AWS Regions file is blank

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#60] opened 2017-11-29 20:14 UTC
On every new build the AWS regions file is empty.  It should be seeded with some regions (or even just 1 local region) and have a post-process job to refresh from the json ranges page

**Comment by markofu** [comment] 2017-11-29 21:19
Seems to be failing for the first time on launch, but @tomvachon confirmed that a re-launch or restart of the `scheduler` results in the file being populated.

**Comment by TheM0ng00se** [comment] 2017-11-30 18:48
During my testing I found that the regional collector would simply silently not run...I'll have a dig into this.

**Comment by TheM0ng00se** [comment] 2017-11-30 20:27
@tomvachon : This should be fixed by #67 and #68 . Can you please confirm?

**Comment by markofu** [comment] 2017-12-01 00:20
As per Tom's comment in Slack, this seems fixed so closing. Can reopen obviously.

**Closed by markofu** 2017-12-01 00:20 UTC
Labels: bug, minor
