### ISSUE TITLE
AWS Regions List include AWS Edge Locations

### ISSUE THREAD

**Issue by TheM0ng00se** [RiotGames/cloud-inquisitor#100] opened 2018-02-06 03:28 UTC
CINQ may exhibit errors during collection such as:

botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.eu-north-1.amazonaws.com/"

This is a result of how regions are populated:

https://github.com/RiotGames/cloud-inquisitor/blob/master/backend/cloud_inquisitor/__init__.py#L274

Should consider using only regions marked as "service" : "EC2", or have a way of tagging/filtering edge locations such that collectors/auditors aren't operating against them.

**Comment by TheM0ng00se** [comment] 2018-02-06 16:21
Appears this is handled by the config item:

ignored_aws_regions_regexp

Going to leave the issue for now but not mark as a bug since this is intended behaviour. May consider changing the defaults or improving documentation.

**Comment by bunjiboys** [comment] 2018-02-06 19:13
In this case, it wouldn't make a difference since eu-north-1 is not an Edge region, is a new region Amazon is getting ready to launch, and the information for the region is usually populated into the ip-ranges.json file before the region itself launches (usually a month or two before in my experience).

Closing this issue, as its not a bug / issue in the code, with a note to improve documentation around the filter.

**Closed by bunjiboys** 2018-02-06 19:13 UTC
Labels: documentation, investigation
